Authentication and Dashboard
UtsavSomaiya/laravel-pos pull request #1
Opened 2022-05-25 03:31 UTC by UtsavSomaiya

- [ ] In this PR we can add the register page, login page & dashboard page.

2022-05-25 13:37 UTC, hirenkeraliya requested changes

2022-05-25 13:37 UTC, hirenkeraliya commented on resources/views/admin/auth/layout.blade.php
> +    <script src="{{ asset('js/alertify.js') }}"></script>
why script here?

2022-05-25 13:37 UTC, hirenkeraliya commented on resources/views/admin/auth/layout.blade.php
> +    <script src="{{ asset('js/alertify.js') }}"></script>
Never miss the indentation

2022-05-25 13:37 UTC, hirenkeraliya commented on resources/views/admin/auth/layout.blade.php
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="a
really needed? if yes then for what?

2022-05-25 13:37 UTC, hirenkeraliya commented on resources/views/admin/auth/login.blade.php
> +                <input type="password" class="form-control form-control-lg @error('password') is-invalid @enderror" placeholder="Password" name="password" required>
jyare lambu thay tyare niche padta nathi shikhvadyu?

2022-05-25 13:37 UTC, hirenkeraliya commented on resources/views/admin/auth/login.blade.php
> +        <a href="/admin/register" class="btn">Sign Up</a>
use route naming

2022-05-25 13:37 UTC, hirenkeraliya commented on resources/views/admin/auth/register.blade.php
> +                        {{ $message }}
make some spacing and proper indentation in all HTML files

2022-05-25 13:37 UTC, hirenkeraliya commented on routes/web.php
> +    });
check route documentation

2022-05-26 03:24 UTC, UtsavSomaiya commented on app/Http/Controllers/Admin/AdminAuthController.php
> +            'name' => ['required','exists:admins,name','max:255'],
On the register page, I am checking the unique username so it can be hacked also Is it removed or not?

2022-05-26 06:39 UTC, hirenkeraliya requested changes

2022-05-26 06:39 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/AdminAuthController.php
> +            return to_route('dashboard')->with(['success'=>'Welcome back!!']);
```suggestion
            return to_route('dashboard')->with(['success'=>'Loggeed in successfully.']);
```

2022-05-26 06:39 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/AdminAuthController.php
> +            'success' => 'Good Bye!!'
```suggestion
            'success' => 'Logged out successfully.'
```

2022-05-26 06:39 UTC, hirenkeraliya commented on database/factories/AdminFactory.php
> +            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
```suggestion
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',  // password
```

2022-05-26 06:39 UTC, hirenkeraliya commented on database/migrations/2022_05_24_072656_create_admins_table.php
>              $table->timestamp('email_verified_at')->nullable();
why this column exists?

2022-05-26 06:39 UTC, hirenkeraliya commented on resources/css/app.css
> +
not needed.

2022-05-26 06:39 UTC, hirenkeraliya commented on resources/views/admin/layout.blade.php
> +        <script src="{{ asset('js/alertify.js') }}"></script>
1 var kidhu hoy etle aakhi pr ma badhe sarkhu thy javu joyye

2022-05-26 06:39 UTC, hirenkeraliya commented on resources/views/admin/layout.blade.php
> +                            <a class="nav-link text-light" href="/admin/dashboard">
still direct url's

2022-05-26 06:39 UTC, hirenkeraliya commented on routes/web.php
> +    Route::post('/admin/register', [AdminAuthController::class,'register']);
```suggestion
    Route::view('/admin', 'admin.auth.login')->name('login');
    Route::post('/admin', [AdminAuthController::class,'login']);
    
    Route::view('/admin/register', 'admin.auth.register')->name('register');
    Route::post('/admin/register', [AdminAuthController::class,'register']);
```

2022-05-26 13:03 UTC, hirenkeraliya requested changes

2022-05-26 13:03 UTC, hirenkeraliya commented on database/factories/AdminFactory.php
> +            'name' => $this->faker->name(),
still name

2022-05-26 13:03 UTC, hirenkeraliya commented on public/js/alertify.js
> +/**
use minified css and js

2022-05-27 13:57 UTC, hirenkeraliya approved these changes

2022-05-27 13:58 UTC, merged