Product CRUD
UtsavSomaiya/laravel-pos pull request #10
Opened 2022-06-14 12:01 UTC by UtsavSomaiya

2022-06-14 12:24 UTC, hirenkeraliya requested changes

2022-06-14 12:24 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +            'image' => ['image'],
aani file banavi hti e kya?

2022-06-14 12:24 UTC, hirenkeraliya commented on resources/views/admin/products/form.blade.php
> +                            value="@isset($product){{ $product->name }}@else{{ old('name') }}@endisset"
```suggestion
                            value="{{ isset($product) ? $product->name : old('name') }}"
```

2022-06-14 12:24 UTC, hirenkeraliya commented on resources/views/admin/products/form.blade.php
> +                        @enderror
make some spacing in all the html files.

Currently it's looks like a dustbin

2022-06-14 12:24 UTC, hirenkeraliya commented on routes/web.php
> +    Route::post('/admin/products/delete/{product}', [ProductController::class,'delete'])->name('products.delete');
use controller grouping and name prefix

2022-06-15 03:06 UTC, UtsavSomaiya commented on app/Http/Controllers/Admin/ProductController.php
> +            'image' => ['image'],
That file is only created in Discount Module because the validation length is very long.

2022-06-15 09:19 UTC, hirenkeraliya requested changes

2022-06-15 09:19 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +        }
```suggestion
        $productsExists = Product::where('category_id', $category->id)->exists();

        if ($productsExists) {
            return back()->with([
                'error' => 'This category depends on some of the products'
            ]);
        }
```

2022-06-15 09:19 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +            'image' => ['image'],
required image

2022-06-15 09:19 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +            'image' => ['image'],
make it dynamic.

2022-06-15 09:19 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +        $product ??= new Product();
never do like this use route name to identify it's update or add

2022-06-15 09:19 UTC, hirenkeraliya commented on resources/views/admin/products/form.blade.php
> +                            @php $taxes = App\Models\Product::TAXES; @endphp
never call any class directly in the view files. Pass this from the controller

2022-06-15 09:19 UTC, hirenkeraliya commented on resources/views/admin/products/form.blade.php
> +                            @php $taxes = App\Models\Product::TAXES; @endphp
As per the MCV Structure.

2022-06-15 09:19 UTC, hirenkeraliya commented on resources/views/admin/products/form.blade.php
> +                                    @endisset
```suggestion
                                    {{ isset($product) && old('tax', $product->tax) === $taxes[$i] ? 'selected' }}
```

2022-06-15 09:19 UTC, hirenkeraliya commented on routes/web.php
> +    });
read my comment I suggested for the route name prefix. you have changed the URL prefix

2022-06-16 12:27 UTC, UtsavSomaiya commented on resources/views/admin/products/form.blade.php
> +                                    @endisset
`{{ old('tax', isset($product) ?  intval($product->tax) : '') === $taxes[$i] ? 'selected' :  '' }}`

2022-06-17 12:11 UTC, hirenkeraliya approved these changes

2022-06-17 12:12 UTC, merged