Categories crud
UtsavSomaiya/laravel-pos pull request #3
Opened 2022-05-26 07:21 UTC by UtsavSomaiya

- [ ] In this PR we can perform category CRUD.

2022-05-27 14:06 UTC, hirenkeraliya requested changes

2022-05-27 14:06 UTC, hirenkeraliya commented on app/Models/Category.php
> +    }
remove this

2022-05-27 14:06 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function show()
index it's not an show

2022-05-27 14:06 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function show()
same rename everywhere

2022-05-27 14:06 UTC, hirenkeraliya commented on resources/views/admin/categories/show.blade.php
> +                                <tr>
use forelse

2022-05-28 03:13 UTC, UtsavSomaiya commented on app/Http/Controllers/Admin/CategoryController.php
> +        return to_route('categories-list')->with(
laravel url(route) name => `rajan-parmar` (General Case)

2022-05-28 07:47 UTC, hirenkeraliya requested changes

2022-05-28 07:47 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function index()
index method pela aave pa6i store edit update delete

2022-05-28 07:47 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +            'name' => ['required','min:3','max:255']
Unique validation?

2022-05-28 07:47 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +        $category = Category::findOrFail($categoryId)->first();
`->first()` not needed.

2022-05-28 07:47 UTC, hirenkeraliya commented on database/migrations/2022_05_26_070834_create_categories_table.php
> +            $table->string('name');
need to declare unique

2022-05-28 07:47 UTC, hirenkeraliya commented on resources/views/admin/categories/add.blade.php
> +                    <a href="{{ route('categories_list') }}" class="btn btn-light mt-3">Cancel</a>
only categories

2022-05-28 07:47 UTC, hirenkeraliya commented on resources/views/admin/categories/index.blade.php
> +                                    <a href="{{ route('category_edit', ['id' => $category->id ]) }}"
categories.edit

2022-05-28 07:47 UTC, hirenkeraliya commented on resources/views/admin/categories/index.blade.php
> +                        <a href="{{ route('category_add') }}" class="link-dark h6">Add New Category</a>
categories.add

2022-05-28 07:47 UTC, hirenkeraliya commented on resources/views/admin/categories/index.blade.php
> +                                        action="{{ route('category_delete', ['id' => $category->id]) }}"
categories.delete

2022-05-28 07:47 UTC, hirenkeraliya commented on resources/views/admin/categories/index.blade.php
> +                            <th colspan="2">Action</th>
why colspan in the header?

2022-05-30 06:02 UTC, hirenkeraliya requested changes

2022-05-30 06:02 UTC, hirenkeraliya commented on resources/views/admin/categories/add.blade.php
> +                        @endisset
`{{ $category ? 'Update' : 'Submit' }}`

2022-05-30 06:02 UTC, hirenkeraliya commented on routes/web.php
> +    Route::post("admin/categories/edit/{id}", [CategoryController::class,'update']);
```suggestion
    Route::get('/admin/categories', [CategoryController::class,'index'])->name('categories');
    Route::view('/admin/categories/add', 'admin.categories.add')->name('categories.add');
    Route::post('admin/categories', [CategoryController::class,'store']);
    Route::get("admin/categories/edit/{category}", [CategoryController::class,'edit'])->name('categories.edit');
    Route::put("admin/categories/edit/{category}", [CategoryController::class,'update']);
    Route::post("admin/categories/delete/{id}", [CategoryController::class,'delete'])->name('categories.delete');
```

2022-05-30 06:02 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/CategoryController.php
> +        Category::findOrFail($categoryId)->delete();
you can use model binding like

```suggestion
    public function delete(Category $category)
    {
        $category->delete();
```

2022-05-30 13:30 UTC, UtsavSomaiya commented on resources/views/admin/categories/add.blade.php
> +                        @endisset
`{{ isset($category) ? 'Update' : 'Submit' }}`

2022-05-31 04:59 UTC, hirenkeraliya requested changes

2022-05-31 04:59 UTC, hirenkeraliya commented on routes/web.php
> +    Route::post('admin/categories', [CategoryController::class,'store']);
name should be `categories.store` and use it on the form

2022-06-03 06:59 UTC, hirenkeraliya approved these changes

2022-06-03 06:59 UTC, merged