Product
UtsavSomaiya/laravel-pos pull request #4
Opened 2022-05-26 07:32 UTC by UtsavSomaiya

- [ ] In this PR we can perform category CRUD

2022-06-03 07:14 UTC, hirenkeraliya requested changes

2022-06-03 07:14 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +            'name' => ['required','min:3','max:255','unique:products,name'],
min:3 not needed

2022-06-03 07:14 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +            'success' => 'Products added successfully.'
```suggestion
            'success' => 'Product added successfully.'
```

2022-06-03 07:14 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +        $categories = Category::findOrFail($product->category_id)->get();
why used `->get()` is there any reason?

2022-06-03 07:14 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +            Storage::delete('public/image'.'/'.$product->image);
delete after storing a file

2022-06-03 07:14 UTC, hirenkeraliya commented on app/Models/Product.php
> +    protected $fillable = ['name','price','category_id','tax','stock','image','path'];
always space after the `,` sign

2022-06-03 07:14 UTC, hirenkeraliya commented on database/migrations/2022_05_25_110122_create_products_table.php
> +            $table->float('price');
use decimal

2022-06-03 07:14 UTC, hirenkeraliya commented on database/migrations/2022_05_25_110122_create_products_table.php
> +            $table->foreign('category_id')->references('id')->on('categories');
```suggestion
            $table->foreignId('category_id')->constrained();
```

2022-06-03 07:14 UTC, hirenkeraliya commented on database/migrations/2022_05_25_110122_create_products_table.php
> +            $table->float('tax');
why tax? as per your answer of my question `Tax is Cart Wide`

2022-06-03 07:14 UTC, hirenkeraliya commented on public/css/admin/custom.css
> +img{
proper indentation

2022-06-03 07:14 UTC, hirenkeraliya commented on public/js/custom.js
> +        });
make this dynamic

2022-06-03 07:14 UTC, hirenkeraliya commented on resources/views/admin/products/add.blade.php
> +                    @empty($product) action="{{ route('products.store') }}" @endempty
what if user come for the edit product

2022-06-03 07:14 UTC, hirenkeraliya commented on resources/views/admin/products/add.blade.php
> +                                @else
make this dynamic

2022-06-03 07:14 UTC, hirenkeraliya commented on resources/views/admin/products/index.blade.php
> +                        @forelse($products as $key => $product)
what use of `$key`

2022-06-03 07:32 UTC, hirenkeraliya requested changes

2022-06-03 07:32 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +        return view('admin.products.add', compact('categories'));
rename add to form

2022-06-06 05:51 UTC, UtsavSomaiya commented on app/Http/Controllers/Admin/ProductController.php
> +            Storage::delete('public/image'.'/'.$product->image);
> delete after storing a file

delete after updating a file

2022-06-07 07:27 UTC, hirenkeraliya requested changes

2022-06-07 07:27 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/ProductController.php
> +        ]);
duplicate code

2022-06-07 07:27 UTC, hirenkeraliya commented on database/migrations/2022_05_25_110122_create_products_table.php
> +            $table->decimal('price');
```suggestion
            $table->decimal('price', 10, 2);
```

2022-06-07 07:27 UTC, hirenkeraliya commented on database/migrations/2022_05_25_110122_create_products_table.php
> +            $table->decimal('tax');
```suggestion
            $table->decimal('tax', 5, 2);
```

2022-06-07 07:27 UTC, hirenkeraliya commented on public/js/custom.js
> +    alertify.confirm('Delete  '+ type, 'Are you sure to delete this ' + type + '?', function () {
```suggestion
    alertify.confirm('Delete  '+ type, 'Are you sure you want to delete this ' + type + '?', function () {
```

2022-06-14 10:44 UTC, hirenkeraliya commented
I have checked the 65% percent PR and you pushed the new code of the export in the same pr. What should I do now?

2022-06-14 10:44 UTC, closed without merging