Discounts CRUD
UtsavSomaiya/laravel-pos pull request #5
Opened 2022-05-30 05:02 UTC by UtsavSomaiya

- [ ] In this PR we can perform discounts CRUD with tier.

2022-06-03 07:40 UTC, hirenkeraliya requested changes

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +            'category' => ['required'],
check in database it's exists or not

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +        $MainDiscount = [
variable name in camel case

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +        $discount = $request->validate([
validatedData

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +            for ($i = 0; $i < sizeof($discount['minimum_spend_amount']); $i++) {
use count

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +                ];
no need to declare use directly

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +        return view('admin.discounts.add', compact('discount', 'products'));
rename add to form

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +            'category' => ['required'],
category_id

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +                    if (request('type') == 0 && (int) $value > 100) {
request()->input('type')

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +                    if (request('type') == 0 && (int) $value > 100) {
why `(int)`

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +                    ->where('discount_id', $discount->id)
devide code into a diffrent methods

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +        $discount->update(['status' => $request->status]);
validation of status?

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Models/GiftDiscount.php
> +    public function products()
singular

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Models/Product.php
> +    public function giftDiscount()
plural

2022-06-03 07:40 UTC, hirenkeraliya commented on app/Models/Product.php
> +    public function giftDiscount()
i think this relation is not needed

2022-06-03 07:40 UTC, hirenkeraliya commented on database/migrations/2022_05_26_083913_create_discounts_table.php
> +            $table->boolean('category');
why boolean?

2022-06-03 07:40 UTC, hirenkeraliya commented on public/js/discount.js
> +        status = status - 1;
proper if else condition

2022-06-03 07:40 UTC, hirenkeraliya commented on public/js/discount.js
> +if (document.getElementById('discount-category') != null) {
why javascript?

2022-06-03 07:40 UTC, hirenkeraliya commented on public/js/discount.js
> +    if (category === '1')
if (condition) {

2022-06-03 07:40 UTC, hirenkeraliya commented on public/js/discount.js
> +        if (flag == 2) {
no need of if condition

2022-06-03 07:40 UTC, hirenkeraliya commented on resources/views/admin/discounts/add.blade.php
> +                        <!-- Template render here!! -->
what is template specify proper name

2022-06-03 07:40 UTC, hirenkeraliya commented on resources/views/admin/discounts/add.blade.php
> +    @if($errors->count() > 0)
double blank line

2022-06-07 10:47 UTC, hirenkeraliya requested changes

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +        DiscountServices::createOrUpdateDiscount($validatedData, new Discount());
saveDetails

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Http/Controllers/Admin/DiscountController.php
> +            'type' => ['required_if:promotion_type,in:"1"'],
move to form request

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Models/Discount.php
> +    ];
```suggestion
    public const STATUS = [
        0 => 'Active',
        1 => 'Inactive',
    ];
```
```suggestion
    public const STATUS = [
        1 => [1, 'Active'],
        2 => [0, 'Inactive'],
    ];
```

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Models/Discount.php
> +    ];
```suggestion
    public const STATUS = [
        0 => 'Inactive',
        1 => 'Active',
    ];
```

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Models/Discount.php
> +    protected $fillable = ['name','status','promotion_type'];
mistake repeated 3rd time

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Models/Discount.php
> +    protected $fillable = ['name','status','promotion_type'];
mistake repeated 3rd time

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +        if (is_null($discount->id)) {
not good

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +        if (is_null($discount->id)) {
not good

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +        ]);
only for this you change the meaning of the method

2022-06-07 10:47 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +        ]);
only for this you change the meaning of the method

2022-06-07 10:47 UTC, hirenkeraliya commented on database/migrations/2022_05_26_084002_create_price_discounts_table.php
> +            $table->foreign('discount_id')->references('id')->on('discounts')->onDelete('cascade');
repeated 2nd time

2022-06-07 10:47 UTC, hirenkeraliya commented on database/migrations/2022_05_26_084002_create_price_discounts_table.php
> +            $table->foreign('discount_id')->references('id')->on('discounts')->onDelete('cascade');
repeated 2nd time

2022-06-07 10:47 UTC, hirenkeraliya commented on database/migrations/2022_05_26_084002_create_price_discounts_table.php
> +            $table->float('digit');
repeated 2nd time

2022-06-07 10:47 UTC, hirenkeraliya commented on database/migrations/2022_05_26_084002_create_price_discounts_table.php
> +            $table->float('digit');
repeated 2nd time

2022-06-14 10:48 UTC, hirenkeraliya commented on app/Http/Requests/DiscountRequest.php
> +            'type' => ['required_if:promotion_type,in:"1"'],
what is 1?

2022-06-14 10:48 UTC, hirenkeraliya commented on app/Http/Requests/DiscountRequest.php
> +            'type' => ['required_if:promotion_type,in:"1"'],
Never do static coding

2022-06-14 10:48 UTC, hirenkeraliya commented on app/Http/Requests/DiscountRequest.php
> +            'status' => ['required'],
make proper validation `required|boolean`

2022-06-14 10:50 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +            for ($i = 0; $i < count($priceDiscounts); $i++) {
instead of the for loop you can use the foreach loops

2022-06-14 10:50 UTC, hirenkeraliya commented on database/migrations/2022_05_26_084019_create_gift_discounts_table.php
> +            $table->foreignId('product_id')->constrained()->onDelete('cascade');
```suggestion
            $table->foreignId('discount_id')->constrained();
            $table->foreignId('product_id')->constrained();
            $table->decimal('minimum_spend_amount', 10, 2);
```

2022-06-14 10:51 UTC, hirenkeraliya commented on public/js/discount.js
> +    if (status == 0) {
=== strict comparision always.

2022-06-14 10:52 UTC, hirenkeraliya commented on public/js/discount.js
> +var flag;
what is flag?

2022-06-14 10:54 UTC, hirenkeraliya commented on resources/views/admin/discounts/form.blade.php
> +                            value="@isset($discount){{ $discount->name }}@else{{ old('name') }}@endisset"
```suggestion
                            value="{{ $discount ? $discount->name : old('name') }}"
```

2022-06-14 10:54 UTC, hirenkeraliya commented on resources/views/admin/discounts/form.blade.php
> +        {{ view('admin.discounts.gift_discount',compact('products')) }}
always space after the comma

2022-06-14 10:54 UTC, hirenkeraliya commented on resources/views/admin/discounts/form.blade.php
> +        {{ view('admin.discounts.gift_discount',compact('products')) }}
4th time

2022-06-14 10:55 UTC, hirenkeraliya commented on resources/views/admin/discounts/form.blade.php
> +        @if($errors->count() == 0)
always space after if

2022-06-14 10:56 UTC, hirenkeraliya commented on resources/views/admin/discounts/form.blade.php
> +            <script>checkPromotionType();</script>
make some clean and understandable code.

2022-06-14 10:57 UTC, hirenkeraliya commented on resources/views/admin/discounts/price_discount.blade.php
> +                    style="margin-left: 13rem!important;"
inline styles not allowed 2nd time

2022-06-14 10:57 UTC, hirenkeraliya commented on resources/views/admin/layout.blade.php
> +    <script src='https://code.jquery.com/jquery-3.6.0.min.js'></script>
why jquery?

2022-06-14 10:58 UTC, hirenkeraliya commented on routes/web.php
> +
use controller grouping and route prefix feature of the laravel

2022-06-15 09:34 UTC, hirenkeraliya requested changes

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Http/Requests/DiscountRequest.php
> +            'minimum_spend_amount' => ['required','array'],
aakhi pr jovo ane badhe space muko `,` pa6i

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Http/Requests/DiscountRequest.php
> +            'minimum_spend_amount' => ['required','array'],
hve 6elivar kav 6u aa 5th time 6e same mistake

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Http/Requests/DiscountRequest.php
> +            'type' => ['required_if:promotion_type,in:"1"'],
static 1?

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +            for ($i = count($priceDiscounts); $i < count($validatedData['minimum_spend_amount']); $i++) {
foreach loop

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +            for ($i = count($giftDiscounts); $i < count($validatedData['minimum_spend_amount']); $i++) {
foreach

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +            for ($i = 0; $i < count($validatedData['minimum_spend_amount']); $i++) {
foreach

2022-06-15 09:34 UTC, hirenkeraliya commented on app/Services/DiscountServices.php
> +            for ($i = 0; $i < count($validatedData['minimum_spend_amount']); $i++) {
foreach

2022-06-15 09:34 UTC, hirenkeraliya commented on public/js/discount.js
> +        for (i = 0; i < minimumSpendAmounts.length; i++) {
for in

2022-06-15 09:34 UTC, hirenkeraliya commented on public/js/discount.js
> +        if (countOfProduct === minimumSpendContainer.length) {
```suggestion
    if (promotionType === 2 && countOfProduct === minimumSpendContainer.length)) {
```

2022-06-15 09:34 UTC, hirenkeraliya commented on public/js/discount.js
> +    if ((index) > -1) {
```suggestion
    if (index > -1) {
```

2022-06-15 09:34 UTC, hirenkeraliya commented on resources/views/admin/discounts/form.blade.php
> +                            @php $status = App\Models\Discount::STATUS; @endphp
MVC Structure

2022-06-17 13:00 UTC, hirenkeraliya requested changes

2022-06-19 05:38 UTC, UtsavSomaiya commented on resources/views/admin/layout.blade.php
> +    <script src='https://code.jquery.com/jquery-3.6.0.min.js'></script>
Use for update discount status using ajax request.

2022-06-20 06:51 UTC, hirenkeraliya approved these changes

2022-06-20 06:51 UTC, merged